# environment.yml
name: sidig
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pytorch=2.6
  - torchvision
  - pytorch-cuda=12.1
  - pip
  - torchmetrics
  - pip:
    - diffusers
    - transformers
    - accelerate
    - safetensors
    - peft
    - pillow
    - tqdm
